export type UserRole = string

export interface AppMenuItem {
  key: string
  label: string
  viewMobile?: boolean
  children?: AppMenuItem[]
}

export interface LoginUser {
  id: number
  taiKhoan: string
  hoVaTen: string
  avatarUrl?: string | null
  role: UserRole
}

export interface LoginResponse {
  message: string
  accessToken: string
  refreshToken: string
  tokenType: 'Bearer'
  expiresIn: string
  user: LoginUser
  menus: AppMenuItem[]
}

export interface UserListItem {
  id: number
  taiKhoan: string
  hoVaTen: string
  avatarUrl?: string | null
  ngaySinh?: string | null
  gioiTinh?: string | null
  soDienThoai: string
  soGiayTo: string
  diaChi?: string | null
  email?: string | null
  role: UserRole
  roleLabel?: string
  routeIds?: number[]
  assignedRoutes?: Array<{
    id: number
    maTuyen: string
    tenTuyen: string
  }>
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface UserListResponse {
  data: UserListItem[]
  pagination: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

export interface RoleOption {
  code: UserRole
  label: string
  moTa?: string | null
  isActive?: boolean
}

export interface PaginationMeta {
  page: number
  limit: number
  total: number
  totalPages: number
}

export interface PagedResponse<T> {
  data: T[]
  pagination: PaginationMeta
}

export interface ProvinceItem {
  id: number
  maTinh: string
  tenTinh: string
  createdAt: string
  updatedAt: string
}

export interface WardItem {
  id: number
  provinceId: number
  maPhuongXa: string
  tenPhuongXa: string
  province?: {
    id: number
    maTinh: string
    tenTinh: string
  }
  createdAt: string
  updatedAt: string
}

export interface LocalityItem {
  id: number
  wardId: number
  maThonXomTo: string
  tenThonXomTo: string
  ward?: {
    id: number
    maPhuongXa: string
    tenPhuongXa: string
    province?: {
      id: number
      maTinh: string
      tenTinh: string
    }
  }
  createdAt: string
  updatedAt: string
}

export interface RouteItem {
  id: number
  maTuyen: string
  tenTuyen: string
  khuVuc: string
  localityId?: number | null
  staffId?: number | null
  locality?: {
    id: number
    maThonXomTo: string
    tenThonXomTo: string
    ward?: {
      id: number
      maPhuongXa: string
      tenPhuongXa: string
      province?: {
        id: number
        maTinh: string
        tenTinh: string
      }
    }
  } | null
  staff?: {
    id: number
    taiKhoan: string
    hoVaTen: string
    roleCode: string
    isActive?: boolean
  } | null
  createdAt: string
  updatedAt: string
}

export interface ServiceCatalogItem {
  id: number
  maDichVu: string
  tenDichVu: string
  giaDichVu: number
  thuePhanTram: number
  isActive: boolean
  ghiChu?: string | null
  createdAt: string
  updatedAt: string
}

export interface HouseholdItem {
  id: number
  maHoDan: string
  tenChuHo: string
  diaChi: string
  soDienThoai: string
  soGiayTo: string
  ngayCapGiayTo?: string | null
  maSoThue?: string | null
  serviceCatalogId?: number | null
  tuyenThuRacId: number
  isActive: boolean
  createdAt: string
  updatedAt: string
  serviceCatalog?: {
    id: number
    maDichVu: string
    tenDichVu: string
    giaDichVu: number
    thuePhanTram: number
  } | null
  tuyenThuRac?: {
    id: number
    maTuyen: string
    tenTuyen: string
  }
}

export interface MenuItemNode {
  id: number
  menuKey: string
  tenMenu: string
  routePath?: string | null
  parentId?: number | null
  sortOrder: number
  viewMobile: boolean
  isActive: boolean
  children?: MenuItemNode[]
  parent?: {
    id: number
    menuKey: string
    tenMenu: string
  } | null
}

export interface RoleMenuResponse {
  roleCode: string
  menuIds: number[]
}

export interface BillingPeriodItem {
  id: number
  maKy: string
  tenKy: string
  ngayBatDau: string
  ngayKetThuc: string
  isClosed: boolean
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export interface BillingPeriodConfig {
  id: number
  autoCreateEnabled: boolean
  createdAt: string
  updatedAt: string
}

export type InvoicePaymentStatus = 'UNPAID' | 'PAID' | 'OVERDUE' | 'PUBLISHED'

export interface InvoiceItem {
  id: number
  householdId: number
  kyHoaDon: string
  tongTien: number
  thue: number
  trangThaiThanhToan: InvoicePaymentStatus
  hanThanhToan: string
  paymentDate?: string | null
  paymentNote?: string | null
  receiptImageUrl?: string | null
  invoiceSerial?: string | null
  invoiceFkey?: string | null
  invoiceIssuedAt?: string | null
  invoicePublishStatus?: string | null
  invoicePublishMessage?: string | null
  publishedById?: number | null
  publishedByName?: string | null
  collectedById?: number | null
  collectedByName?: string | null
  mergedPeriodCodes?: string | null
  createdAt: string
  updatedAt: string
  household?: {
    id: number
    maHoDan: string
    tenChuHo: string
    diaChi: string
    tuyenThuRac?: {
      id: number
      maTuyen: string
      tenTuyen: string
    } | null
    serviceCatalog?: {
      id: number
      maDichVu: string
      tenDichVu: string
    } | null
  }
}

export interface HouseholdInvoiceHistoryResponse {
  household: {
    id: number
    maHoDan: string
    tenChuHo: string
    diaChi: string
  }
  summary: {
    total: number
    paid: number
    unpaid: number
  }
  invoices: InvoiceItem[]
}

export interface InvoiceReportDetailItem {
  invoiceId: number
  kyHoaDon: string
  maHoDan: string
  tenChuHo: string
  diaChi: string
  tuyenThuRac: string
  nguoiThu: string
  invoiceSerial?: string | null
  invoiceFkey?: string | null
  daPhatHanh: boolean
  tongTien: number
  thue: number
  tongCong: number
  paymentDate?: string | null
  paymentDateKey?: string
}

export interface InvoiceReportSummary {
  soHoDaThu?: number
  soHoaDonDaPhatHanh?: number
  tongTien: number
  thue?: number
  tongCong: number
}

export interface InvoiceReportDailySummary {
  ngayThuTien: string
  soHoDaThu: number
  tongTien: number
}

export interface InvoiceDetailReportResponse {
  data: InvoiceReportDetailItem[]
  summary: InvoiceReportSummary
  pagination: PaginationMeta
}

export interface InvoiceDetailByDateReportResponse extends InvoiceDetailReportResponse {
  tongHopTheoNgay: InvoiceReportDailySummary[]
}

export interface InvoiceRevenueSummaryItem {
  kyHoaDon: string
  tuyenThuRacId?: number | null
  tuyenThuRac: string
  serviceCatalogId?: number | null
  loaiDichVu: string
  tongSoHo: number
  daThuSoHo: number
  chuaThuSoHo: number
  tongTien: number
  tongThue: number
  tongCong: number
  daThuTien: number
  daThuThue: number
  daThuCong: number
  chuaThuTien: number
  chuaThuThue: number
  chuaThuCong: number
}

export interface InvoiceRevenueSummaryResponse {
  data: InvoiceRevenueSummaryItem[]
  summary: {
    tongSoHo: number
    daThuSoHo: number
    chuaThuSoHo: number
    tongTien: number
    tongThue: number
    tongCong: number
    daThuTien: number
    daThuThue: number
    daThuCong: number
    chuaThuTien: number
    chuaThuThue: number
    chuaThuCong: number
  }
  pagination: PaginationMeta
}

export interface SystemParameterItem {
  id: number
  tenThamSo: string
  giaTri: string
  createdAt: string
  updatedAt: string
}

export interface DashboardOverviewResponse {
  filter: {
    kyHoaDons: string[]
  }
  summary: {
    totalHouseholds: number
    totalRoutes: number
    totalUsers: number
    totalInvoices: number
    paidInvoices: number
    unpaidInvoices: number
    overdueInvoices: number
    totalRevenue: number
    paidRevenue: number
    totalNeedToCollect: number
  }
  invoiceStatusChart: Array<{
    key: 'PAID' | 'UNPAID' | 'OVERDUE' | 'PUBLISHED'
    label: string
    count: number
  }>
  invoiceTrendChart: Array<{
    maKy: string
    tenKy: string
    totalInvoices: number
    paidInvoices: number
    unpaidInvoices: number
    overdueInvoices: number
    totalRevenue: number
    paidRevenue: number
    needToCollectRevenue: number
  }>
  staffProgress: Array<{
    staffId: number
    staffName: string
    paidCount: number
    unpaidCount: number
    totalCount: number
    paidPercentage: number
    unpaidPercentage: number
  }>
}
