import {
  BadRequestException,
  Injectable,
  NotFoundException,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateBillingPeriodDto } from './dto/create-billing-period.dto';
import { UpdateBillingPeriodDto } from './dto/update-billing-period.dto';
import { UpdateBillingPeriodConfigDto } from './dto/update-billing-period-config.dto';
import { InvoicesService } from '../invoices/invoices.service';

@Injectable()
export class BillingPeriodsService implements OnModuleInit, OnModuleDestroy {
  private autoCreateTimer: NodeJS.Timeout | null = null;

  constructor(
    private readonly prisma: PrismaService,
    private readonly invoicesService: InvoicesService,
  ) {}

  async onModuleInit() {
    await this.ensureMonthlyPeriodByConfig();

    // Run once per day to auto-create the new monthly period when month changes.
    this.autoCreateTimer = setInterval(() => {
      void this.ensureMonthlyPeriodByConfig();
    }, 24 * 60 * 60 * 1000);
  }

  onModuleDestroy() {
    if (this.autoCreateTimer) {
      clearInterval(this.autoCreateTimer);
      this.autoCreateTimer = null;
    }
  }

  async findAll(page = 1, limit = 20) {
    const normalizedPage = Number.isFinite(page) && page > 0 ? page : 1;
    const normalizedLimit = Number.isFinite(limit)
      ? Math.min(Math.max(limit, 1), 100)
      : 20;
    const skip = (normalizedPage - 1) * normalizedLimit;

    const [data, total] = await this.prisma.$transaction([
      this.prisma.billingPeriod.findMany({
        skip,
        take: normalizedLimit,
        orderBy: { ngayBatDau: 'desc' },
      }),
      this.prisma.billingPeriod.count(),
    ]);

    return {
      data,
      pagination: {
        page: normalizedPage,
        limit: normalizedLimit,
        total,
        totalPages: Math.ceil(total / normalizedLimit),
      },
    };
  }

  async findOne(id: number) {
    const item = await this.prisma.billingPeriod.findUnique({ where: { id } });
    if (!item) {
      throw new NotFoundException('Kỳ hóa đơn không tồn tại');
    }

    return item;
  }

  async create(dto: CreateBillingPeriodDto) {
    const normalized = this.normalizePeriodPayload(dto);
    await this.validatePeriodRange(normalized.ngayBatDau, normalized.ngayKetThuc);

    const created = await this.prisma.billingPeriod.create({
      data: {
        maKy: normalized.maKy,
        tenKy: normalized.tenKy,
        ngayBatDau: normalized.ngayBatDau,
        ngayKetThuc: normalized.ngayKetThuc,
        isClosed: dto.isClosed ?? false,
        isAutoGenerated: false,
      },
    });

    await this.invoicesService.ensureInvoicesForPeriod({
      maKy: created.maKy,
      ngayKetThuc: created.ngayKetThuc,
    });

    return created;
  }

  async update(id: number, dto: UpdateBillingPeriodDto) {
    const existing = await this.findOne(id);

    const nextStart = dto.ngayBatDau ? new Date(dto.ngayBatDau) : existing.ngayBatDau;
    const nextEnd = dto.ngayKetThuc ? new Date(dto.ngayKetThuc) : existing.ngayKetThuc;
    await this.validatePeriodRange(nextStart, nextEnd, id);

    const updated = await this.prisma.billingPeriod.update({
      where: { id },
      data: {
        maKy: dto.maKy?.trim(),
        tenKy: dto.tenKy?.trim(),
        ngayBatDau: dto.ngayBatDau ? new Date(dto.ngayBatDau) : undefined,
        ngayKetThuc: dto.ngayKetThuc ? new Date(dto.ngayKetThuc) : undefined,
        isClosed: dto.isClosed,
      },
    });

    await this.invoicesService.ensureInvoicesForPeriod({
      maKy: updated.maKy,
      ngayKetThuc: updated.ngayKetThuc,
    });

    return updated;
  }

  async remove(id: number) {
    await this.findOne(id);
    await this.prisma.billingPeriod.delete({ where: { id } });
    return { id };
  }

  async getConfig() {
    return this.ensureConfig();
  }

  async updateConfig(dto: UpdateBillingPeriodConfigDto) {
    return this.prisma.billingPeriodConfig.upsert({
      where: { id: 1 },
      update: {
        autoCreateEnabled: dto.autoCreateEnabled,
      },
      create: {
        id: 1,
        autoCreateEnabled: dto.autoCreateEnabled,
      },
    });
  }

  async runAutoCreateNow() {
    await this.ensureMonthlyPeriodByConfig();
    return { message: 'Đã kiểm tra và tạo kỳ hóa đơn tự động (nếu thiếu)' };
  }

  private async ensureConfig() {
    return this.prisma.billingPeriodConfig.upsert({
      where: { id: 1 },
      update: {},
      create: {
        id: 1,
        autoCreateEnabled: true,
      },
    });
  }

  private async ensureMonthlyPeriodByConfig() {
    const config = await this.ensureConfig();
    if (!config.autoCreateEnabled) {
      return;
    }

    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth();
    const start = new Date(year, month, 1, 0, 0, 0, 0);
    const end = new Date(year, month + 1, 0, 23, 59, 59, 999);
    const maKy = `${year}-${String(month + 1).padStart(2, '0')}`;
    const tenKy = `Kỳ ${String(month + 1).padStart(2, '0')}/${year}`;

    const period = await this.prisma.billingPeriod.upsert({
      where: { maKy },
      update: {
        tenKy,
        ngayBatDau: start,
        ngayKetThuc: end,
      },
      create: {
        maKy,
        tenKy,
        ngayBatDau: start,
        ngayKetThuc: end,
        isAutoGenerated: true,
      },
    });

    await this.invoicesService.ensureInvoicesForPeriod({
      maKy: period.maKy,
      ngayKetThuc: period.ngayKetThuc,
    });
  }

  private normalizePeriodPayload(dto: CreateBillingPeriodDto) {
    const ngayBatDau = new Date(dto.ngayBatDau);
    const ngayKetThuc = new Date(dto.ngayKetThuc);

    if (Number.isNaN(ngayBatDau.getTime()) || Number.isNaN(ngayKetThuc.getTime())) {
      throw new BadRequestException('Ngày bắt đầu hoặc ngày kết thúc không hợp lệ');
    }

    const maKy = dto.maKy?.trim() || this.toPeriodCode(ngayBatDau);
    const tenKy = dto.tenKy?.trim() || `Kỳ ${this.toPeriodLabel(ngayBatDau)}`;

    return { maKy, tenKy, ngayBatDau, ngayKetThuc };
  }

  private async validatePeriodRange(start: Date, end: Date, excludeId?: number) {
    if (start > end) {
      throw new BadRequestException('Ngày bắt đầu phải nhỏ hơn hoặc bằng ngày kết thúc');
    }

    const overlap = await this.prisma.billingPeriod.findFirst({
      where: {
        ...(excludeId ? { id: { not: excludeId } } : {}),
        AND: [{ ngayBatDau: { lte: end } }, { ngayKetThuc: { gte: start } }],
      },
      select: { id: true, maKy: true },
    });

    if (overlap) {
      throw new BadRequestException(`Khoảng ngày bị trùng với kỳ ${overlap.maKy}`);
    }
  }

  private toPeriodCode(date: Date) {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
  }

  private toPeriodLabel(date: Date) {
    return `${String(date.getMonth() + 1).padStart(2, '0')}/${date.getFullYear()}`;
  }
}
